# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-01-08T23:46:13+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any

from pydantic import BaseModel, conint


class Sex(Enum):
    male = 'male'
    female = 'female'


class AdoptionStatus(Enum):
    available = 'available'
    pending = 'pending'
    adopted = 'adopted'


class Pet(BaseModel):
    id: conint(ge=1) | None = None
    name: str
    date_of_birth: date | None = None
    species: str
    breed: str | None = None
    colour: str | None = None
    age: conint(ge=0) | None = None
    sex: Sex | None = None
    weight: Any | None = None
    neutered: bool | None = None
    vaccinated: bool | None = None
    adoption_status: AdoptionStatus | None = None
